[[Xorg_xcb_util_keysyms]]
arch = "armv7l"
git-tree-sha1 = "6ad02cf812933a8fe93de5a6d6a4a76c9ebf751f"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "6ee50a84a5ae2600de6064a3ed2f07010eaca45c84b46efa2dc9fec503f1072c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.arm-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "x86_64"
git-tree-sha1 = "fb43096db43c33d0f7726706949c1c00824e6c9a"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "dff3b3cb2654bc4866ebe3f0afcf837feb0f96e169e5da1fa07cea29bf24ae67"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "aarch64"
git-tree-sha1 = "8f8188915ec17d45625bfec8a127dbd47b813300"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "4fb94a9c00289c23d8c0c46d184921749acc26dd97fa3b20a0a2ef64ee10a3ad"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "i686"
git-tree-sha1 = "7666b71bd16d2465eb4a536b3851df4b52fc2e7c"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "b84d9dc27e4f9e3d6ac8a51f562b104988697585bf9f5ddc55d7178be502c184"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "aarch64"
git-tree-sha1 = "0600190eb9333fd869e1e451f348150d69369fdc"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "a0ff305e113f766dfaa2c5bc1efe5fc0e22e6d38c012f7b92cef777e5be3f881"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "x86_64"
git-tree-sha1 = "6a388bf56680dfd78dee1b1a4dfc1812dd68beaf"
os = "freebsd"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "e4b83c54c4f98c50f9fc60a10241eb1543da8e1ddb1d48471e576484a198621c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "powerpc64le"
git-tree-sha1 = "5b71b28a4ed78ad00d1a33ebaba1bd0fa676d789"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "d0f66bdd043d95edd67eacc2f46d41c580fc97cdf48055196301d229774b6086"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "i686"
git-tree-sha1 = "6e73371da90c65bd4d76f1363299e11733bdf1fc"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "331dedd2b1f34a29afb089b5d3c628f0abdcca1e6efc3b668ab659393bbb09fd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "x86_64"
git-tree-sha1 = "13fdcbcdf139d660790b598216850b8a6562fb24"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "144ca7df53083416e7856f48665f2929ed417b0915389004389a8953e0629abe"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_keysyms]]
arch = "armv7l"
git-tree-sha1 = "b0744f6c8cb23e761177ade4f8b2658a040a0aa5"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_keysyms.download]]
    sha256 = "ed7443b24413406d4854e3d1beac8c5ab76f258d00d3308086afc5b4e0ffedc7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_keysyms_jll.jl/releases/download/Xorg_xcb_util_keysyms-v0.4.0+0/Xorg_xcb_util_keysyms.v0.4.0.arm-linux-musleabihf.tar.gz"
